### ISSUE TITLE
区间日历选择器IOS点击事件不兼容

### ISSUE THREAD

**Issue by kite-app** [AlanZhang001/ui-mcalendar#1]
@AlanZhang001 安卓选择区间日期正常，IOS选择日期点击事情失效

**Comment by AlanZhang001** [comment]
请问安装的是最近版本v1.1.9 吗，实际使用过组件的项目有正常上线的案例，如果不是配置不到导致的问题，请说下您使用的ios版本和浏览器

**Comment by AlanZhang001** [comment]
@kite-app

**Comment by kite-app** [comment]
@AlanZhang001 是安装了最近版本v1.1.9，IOS10.1.1系统，微信客户端，safari都不支持，日历的日期无法点击

**Comment by kite-app** [comment]
@AlanZhang001 您好，麻烦请问下今晚能否调好那个BUG呢？

**Comment by AlanZhang001** [comment]
@kite-app 我目前在ios中能正常使用，你是不是配置错了，能发下你的配置看看吗？

**Comment by AlanZhang001** [comment]
你试git上的一个demo，https://github.com/futuweb/ui-mcalendar/blob/master/example/multiple-select.html，你可clone之后试试ios的效果 @kite-app

**Comment by kite-app** [comment]
@AlanZhang001 http://ubus.cdnzz.com/system_manage/app/login.html#/data 选择日期哪里

**Comment by kite-app** [comment]
@AlanZhang001 头部是不是要引入这两个才兼容IOS 
<meta name="apple-mobile-web-app-capable" content="yes">
 <meta name="apple-mobile-web-app-status-bar-style" content="black">

**Comment by AlanZhang001** [comment]
@kite-app 这2个只是用来改变 Safari 样式的，和兼容无关。你本地还是不能运行吗？

**Comment by kite-app** [comment]
@AlanZhang001 
 		var futuCalendar = require('index');
		var input = document.querySelector("#calendar");
	        var d = new Date();
	   	var cal = new futuCalendar({
	        wrapper:".wrapper",
	        initshow: false,
	        autohide: false,
	        hasMask: true,
	        startEndSelect: 2017,
	        startEndDataFormat: "yyyy/MM/dd至yyyy/MM/dd",
	        showToolBar: true,
	        toolTemplateStr: function(){
	            return document.querySelector("#selectDate").innerHTML;
	        },
	        //toolTemplateStr:document.querySelector("#selectDate").innerHTML
	        toolList: [{
	            text:"最近一周",
	            className:"nearweak",
	            action:function(instance,item){
	                instance.setSEPoints(+d - 6*24*3600*1000,d,function(){
	                });
	            }
	        },
	        {
	            text:"确定",
	            className:"nearweak2",
	            action:function(instance,item){
	                instance.hide();
	                item.classList.add("hello");
	            }
	        }],
	        valueTarget:input
	    });

**Comment by kite-app** [comment]
@AlanZhang001  配置就这样啊

**Comment by kite-app** [comment]
@AlanZhang001 http://ubus.cdnzz.com/project/app/system_manage/login.html#/data
您用IOS看看中间选择日历插件哪里吧，试试选择日期的效果吧

**Comment by AlanZhang001** [comment]
我去掉了toolTemplateStr，我用你的配置在ios可正常使用。

你提供的地址需要账户密码

**Comment by AlanZhang001** [comment]
@kite-app

**Comment by AlanZhang001** [comment]
![img_1312](https://cloud.githubusercontent.com/assets/9763641/21426525/4b179e50-c88a-11e6-8f2b-46eeb7b4a9b0.png)
@kite-app

**Comment by kite-app** [comment]
@AlanZhang001 这个是我在测试的一个项目， 账号：zhansan 密码：zhansan1234，你看看是不是IOS不行

**Comment by kite-app** [comment]
@AlanZhang001 这个东西toolTemplateStr在哪里去的，需要重新下载吗？

**Comment by kite-app** [comment]
@AlanZhang001 我在我的配置去掉这个toolTemplateStr.在手机上测试还是不行

**Comment by kite-app** [comment]
@AlanZhang001 解决了

**Comment by kite-app** [comment]
IOS要依赖这个   <div class="wrapper"></div>标签，安卓，电脑版不需要

**Comment by AlanZhang001** [comment]
快哭了，我也是纳闷半天。解决了就好。
这个元素是必须的，表示日历放在哪里；我要加强下异常提示。

**Comment by AlanZhang001** [comment]
@kite-app

**Comment by kite-app** [comment]
@AlanZhang001 不加那个div为wrapper的标签，为什么chrome模拟手机端，还有真机安卓端也可以点击，就IOS不行，我也郁闷了半天

**Comment by AlanZhang001** [comment]
@kite-app 如果开发者没有指定有效的wrapper，wrapper默认为doument.body，组件dom结构也是放在这里面，组件的事件都是委托到wrapper来处理的，这里也不可能为每个日期元素绑定事件; 然后问题的关键来了，IOS上有个奇怪的bug， 对于div, span此类元素，click事件是无法通过委托给body处理的；见https://happycoder.net/solve-ios-safari-click-event-bug/ 
解决的办法有，
1.  给具体的元素（组件中日期元素是li包裹的span）加上样式（cursor：pointer）；但是不能保证组件使用者会加上这个样式。
2.  使用a标签替换span；但是不能保证开发者自己去写组件的html模板的时候，就是使用span。
3. 第三种，不要绑定事件到body上，这种方式更直接吧。

这个问题，我查很久才明白的！
