### ISSUE TITLE
绑定DOM的事件，切换月份会丢失，用事件委托也绑不上点击事件，只能绑on，click事件

### ISSUE THREAD

**Issue by kite-app** [AlanZhang001/ui-mcalendar#2]
@AlanZhang001 打开插件，没切换月份，点击事件是可以的，切换月份，我绑的点击事件就失效了$('body').delegate('.tool-bar .nearweak2','click',function(){})
$('.nearweak2').on('click', function() {})

**Comment by AlanZhang001** [comment]
@kite-app 
1. 工具栏的点击事件通过action这个字段去指定，是不需要额外去绑定的。
2. 日历上的事件 组件做了停止冒泡stopPropagation的处理，使用委托自然不行。
3. 每次切换日历， 日历上的元素是重新生成的（我承认，这里设计时考虑不周全），所以直接在某个元素上绑定的事件不具有持久性。

所以你在配置工具栏的时候应该通过acttion字段去配置响应事件

**Comment by AlanZhang001** [comment]
@kite-app 如果你非要自己去指定，在selectMonth这个函数中里面去 进行事件绑定吧
`new futuCalendar({
.....
,
selectMonth: function(){
    $(".nearweak2").on({
        click: function(){
            alert(1);
        }
    });
}

})`

**Comment by kite-app** [comment]
@AlanZhang001 看了你写的文档好久，在你的toolList.action的回调中去绑定事件了。给确定绑定事件我要这样写dateFun.foo().option.toolList[1].action = function(instance,item){   ............   }

**Comment by AlanZhang001** [comment]
@kite-app 直接初始化的时候就可以指定呀
![image](https://cloud.githubusercontent.com/assets/9763641/22014205/947f40e6-dcd7-11e6-8687-b929747233db.png)

**Comment by AlanZhang001** [comment]
@kite-app 另外提醒一句，事件委托现在都推荐使用on，delegate 早已不推荐使用了
